backend:
  image: tamar746968/app-translator-backend:latest
  replicas: 1                     # שנה ל-replicas בהתאם למה שהטמפלייט מחפש
  port: 3001
  env:                            # להוריד את הסולמית מתחילת השורה!
    translatorHost: "translator-service" # להוריד את הסולמית מתחילת השורה!

frontend:
  image: tamar746968/app-translator-frontend:latest 
  port: 80
  replicaCount: 1
  resourcess: 
    

translator:
  image: libretranslate/libretranslate:latest
  port: 5000
  replicaCount: 1

database:
  image: postgres:15
  name: translations
  user: postgres
  password: bXlwYXNzd29yZA==
  replicaCount: 1
  storage: 1Gi

volume:
  init:
    sql: |
      CREATE TABLE IF NOT EXISTS translations (
        id SERIAL PRIMARY KEY,
        source_text TEXT NOT NULL,
        target_lang VARCHAR(10) NOT NULL,
        translated_text TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      );
