name: CI Backend        

on:                       
  push:
    branches: [main, ci/cd]   
    paths:
      - 'backend/**'             
      - '.github/workflows/ci-backend.yml'  
  pull_request:
    branches: [main]         
    paths:
      - 'backend/**'