name: ci-frontend
on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - '.github/workflows/ci-frontend.yaml'  
  pull_request:
    branches: [main]
    paths:
      - 'frontend/**'
      - '.github/workflows/ci-frontend.yaml'